### PR TITLE
Modify build so that links in docs.micronaut.io are links versioned

### PR DESCRIPTION
**Pull request by timyates**
This PR adds a new feature whereby an environment variable can be used, ie for version 3.10.1:

```
❯ MICRONAUT_RELEASE_VERSION=v3.10.1 ./gradlew build

> Task :renderDocsIndex
Rendering release 3.10.1.html to .../build/generated/3.10.1.html

BUILD SUCCESSFUL in 1s
6 actionable tasks: 2 executed, 4 up-to-date
```

And we end up with:

```
❯ tree build/dist
build/dist
├── 3.10.1.html
└── assets
    ├── images
    │   └── favicon.ico
    ├── javascripts
    │   ├── wpo-minify-footer.js
    │   └── wpo-minify-header.js
    └── stylesheets
        ├── fonts
        │   ├── fa-brands-400.ttf
        │   ├── fa-brands-400.woff
        │   ├── fa-brands-400.woff2
        │   ├── fa-solid-900.ttf
        │   └── fa-solid-900.woff2
        └── style.min.css

5 directories, 10 files
```

Where `3.10.1.html` links point to the version of the modules release in `v3.10.1`

- Anything that cannot be found in the catalog for that version is dropped from the html file.
- Empty categories are dropped from the html file

If you run the above gradle command with `--info`, you'll see that

```
Skipping micronaut-platform as no version found
Skipping micronaut-pulsar as no version found
Skipping micronaut-eclipsestore as no version found
Skipping micronaut-pulsar as no version found
Skipping micronaut-session as no version found
Skipping micronaut-control-panel as no version found
```

But if we generate it for 4.3.4, we just see:

```
❯ MICRONAUT_RELEASE_VERSION=v4.3.4 ./gradlew build --info

...

> Task :renderDocsIndex
Skipping micronaut-netflix as no version found

...

BUILD SUCCESSFUL in 414ms
```

We just skip netflix (which isn't in the release)...

To enable caching in the future, the html is rendered to a `build/generated` folder, and then a copy task copies this and the assets to a `build/dist` folder

Previously, everything just wrote to `build`

We also have a task `renderReleasesDocsIndex` which renders every release in `realeases.yml`, giving us:

```
❯ tree build/dist
build/dist
├── 1.0.1.html
├── 1.0.2.html

<...snip...>

├── 4.3.3.html
├── 4.3.4.html
└── assets
    ├── images
    │   └── favicon.ico
    ├── javascripts
    │   ├── wpo-minify-footer.js
    │   └── wpo-minify-header.js
    └── stylesheets
        ├── fonts
        │   ├── fa-brands-400.ttf
        │   ├── fa-brands-400.woff
        │   ├── fa-brands-400.woff2
        │   ├── fa-solid-900.ttf
        │   └── fa-solid-900.woff2
        └── style.min.css

5 directories, 121 files
```

### CODE REVIEW

**Comment by timyates** [comment]
> For modules, which don't exist in a particular versions we should skip them.

It already does

**Comment by timyates** [comment]
I'm not sure what actions you want...  Looking at the gh-pages branch of micronaut-docs, I'm not sure what does the writing in there...  The assets folder seems to be from micronaut 3?

**Comment by timyates** [comment]
Added the version to the front page so we show

image

**Review by sdelamo — APPROVED** [review]
I have defined the stable version in gradle.properties

**Pull request merged**
